services:
  upload-service:
    build: .
    container_name: upload-service
    restart: always
    ports:
      - "3020:9923"
    volumes:
    - /home/oendel/Documentos/uploads:/var/www/dasssest.com/uploads/
    environment:
      DEV_ENV: development
    networks:
      - dass_private

networks:
  dass_private:
