services:
  upload-service:
    build: .
    container_name: upload-service
    restart: always
    ports:
      - "3020:3020"
    volumes:
      - ${HOST_UPLOAD_FOLDER:-/var/lib/dass/uploads}:/app/uploads
    env_file:
      - .env
    environment:
      UPLOAD_FOLDER: /app/uploads
      DEV_ENV: production
      OTL_METRICS_EXPORTER_URL: http://lgtm:4318/v1/metrics
      OTL_TRACE_EXPORTER_URL: http://lgtm:4318/v1/traces
    networks:
      - dass_private

networks:
  dass_private:
    external: true
