services:
  upload-service:
    build: .
    container_name: upload-service
    restart: always
    ports:
      - "3020:9923"
    volumes:
    - /var/www/dasssest.com/uploads/:/app/uploads
    environment:
      DEV_ENV: production
    networks:
      - dass_private

networks:
  dass_private:
